/* dc_prof.h -- the hardware profile on screen (make HUD=prof, Pinboard #495).
 *
 * Every bench of this port so far is Flycast's clock, and a Dreamcast runs
 * a fight at a quarter of it. Flycast charges nothing for a cache miss, a
 * store into video memory or a seek of the drive, so what the console loses
 * its time to has to be measured on the console. Three instruments, read
 * every 2 s with the rest of the stats (main_dc.c):
 *
 *   - the SH-4's two performance counters: PRFC0 counts the cycles the
 *     pipeline stood still for a data-cache miss, PRFC1 for an instruction-
 *     cache miss. Shown as a share of the window's cycles (200 MHz).
 *   - KallistiOS's PVR stats: the TA's registration and the render time of
 *     the last frame, and the vblanks seen in the window.
 *   - a sampler: TMU1 fires DC_PROF_HZ times a second and the interrupt's
 *     context says where the program was. The PC is looked up in a table of
 *     the program's symbols (dc_prof_map.c, generated by tools/dc_profmap.py
 *     from the linked elf: the Makefile links twice) and counted by symbol
 *     and by group. Shown as each group's share and the hottest symbols.
 *
 * KOS keeps PRFC0 as a 5 ns clock by default; taking it leaves its timers
 * on the TMU's 80 ns one. A sample inside a critical section lands where
 * interrupts came back on. The sampler costs about 0.5% at 2 kHz. */
#ifndef DC_PROF_H
#define DC_PROF_H

#include <kos.h>
#include <dc/perfctr.h>
#include <arch/timer.h>
#include <arch/irq.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef DC_PROF_HZ
#define DC_PROF_HZ 2000
#endif
#define DC_PROF_GROUPS 14
#define DC_PROF_TOP    6

/* dc_prof_map.c (tools/dc_profmap.py): sorted by address */
extern const uint32_t     g_prof_sym_addr[];
extern const uint8_t      g_prof_sym_group[];
extern const char *const  g_prof_sym_name[];
extern const uint32_t     g_prof_sym_n;
extern const char *const  g_prof_group_name[DC_PROF_GROUPS];
extern const uint8_t      g_prof_group_bios;

typedef struct {
    uint32_t *cnt;          /* samples by symbol; [n] below the program (the BIOS) */
    uint32_t  samples;      /* this window's */
    uint64_t  c0, c1;       /* the counters at the window's start */
    size_t    vbl;          /* the PVR's vblank count at the window's start */
    int       on;
} dc_prof_t;

static dc_prof_t g_prof;

/* TMU1's underflow: where was the program? */
static void dc_prof_tick(irq_t code, irq_context_t *ctx, void *data) {
    (void)code; (void)data;
    timer_clear(TMU1);
    uint32_t pc = ctx->pc, n = g_prof_sym_n, idx = n;
    if (pc >= g_prof_sym_addr[0]) {   /* the last symbol at or below pc */
        uint32_t lo = 0, hi = n;
        while (hi - lo > 1) {
            uint32_t mid = (lo + hi) >> 1;
            if (g_prof_sym_addr[mid] <= pc) lo = mid; else hi = mid;
        }
        idx = lo;
    }
    g_prof.cnt[idx]++;
    g_prof.samples++;
}

static int dc_prof_init(void) {
    if (!g_prof_sym_n) return -1;   /* the stub map of the first link */
    g_prof.cnt = calloc(g_prof_sym_n + 1, sizeof *g_prof.cnt);
    if (!g_prof.cnt) return -1;
    perf_cntr_start(PRFC0, PMCR_PIPELINE_FREEZE_BY_DCACHE_MISS_MODE, PMCR_COUNT_CPU_CYCLES);
    perf_cntr_start(PRFC1, PMCR_PIPELINE_FREEZE_BY_ICACHE_MISS_MODE, PMCR_COUNT_CPU_CYCLES);
    g_prof.c0 = perf_cntr_count(PRFC0);
    g_prof.c1 = perf_cntr_count(PRFC1);
    pvr_stats_t st;
    pvr_get_stats(&st);
    g_prof.vbl = st.vbl_count;
    irq_set_handler(EXC_TMU1_TUNI1, dc_prof_tick, NULL);
    timer_prime(TMU1, DC_PROF_HZ, 1);
    timer_start(TMU1);
    g_prof.on = 1;
    return 0;
}

/* The window's five lines, `us` long: the counters and the PVR; the groups
 * (two rows); the hottest symbols (two rows). Starts the next window. */
static void dc_prof_report(uint64_t us, char l[5][96]) {
    if (!g_prof.on) { snprintf(l[0], 96, "prof: off (no symbol map)"); for (int i = 1; i < 5; i++) l[i][0] = 0; return; }
    uint64_t c0 = perf_cntr_count(PRFC0), c1 = perf_cntr_count(PRFC1);
    uint64_t cyc = us * 200u;   /* the SH-4's clock */
    if (!cyc) cyc = 1;
    pvr_stats_t st;
    pvr_get_stats(&st);
    uint32_t n = g_prof_sym_n, total = g_prof.samples ? g_prof.samples : 1;
    snprintf(l[0], 96, "stall d$ %u%% i$ %u%% | pvr rnd %u.%u reg %u.%u ms vbl %u | smp %u",
             (unsigned)((c0 - g_prof.c0) * 100 / cyc), (unsigned)((c1 - g_prof.c1) * 100 / cyc),
             (unsigned)(st.rnd_last_time / 1000000u), (unsigned)(st.rnd_last_time / 100000u % 10),
             (unsigned)(st.reg_last_time / 1000000u), (unsigned)(st.reg_last_time / 100000u % 10),
             (unsigned)(st.vbl_count - g_prof.vbl), (unsigned)g_prof.samples);
    g_prof.c0 = c0; g_prof.c1 = c1; g_prof.vbl = st.vbl_count;
    uint32_t g[DC_PROF_GROUPS] = { 0 };
    uint32_t top[DC_PROF_TOP];
    int ntop = 0;
    for (uint32_t i = 0; i <= n; i++) {
        uint32_t c = g_prof.cnt[i];
        if (!c) continue;
        g[i < n ? g_prof_sym_group[i] : g_prof_group_bios] += c;
        if (i == n) continue;
        /* keep the DC_PROF_TOP largest, in order */
        int k = ntop;
        while (k > 0 && g_prof.cnt[top[k - 1]] < c) k--;
        if (k < DC_PROF_TOP) {
            if (ntop < DC_PROF_TOP) ntop++;
            for (int j = ntop - 1; j > k; j--) top[j] = top[j - 1];
            top[k] = i;
        }
    }
    for (int row = 0; row < 2; row++) {
        char *o = l[1 + row];
        *o = 0;
        for (int i = row * 7; i < row * 7 + 7 && i < DC_PROF_GROUPS; i++)
            o += sprintf(o, "%s%s %u", i == row * 7 ? "" : " ", g_prof_group_name[i], (unsigned)((uint64_t)g[i] * 100 / total));
    }
    for (int row = 0; row < 2; row++) {
        char *o = l[3 + row];
        *o = 0;
        for (int i = row * 3; i < row * 3 + 3 && i < ntop; i++)
            o += sprintf(o, "%s%.16s %u", i == row * 3 ? "" : " | ", g_prof_sym_name[top[i]], (unsigned)((uint64_t)g_prof.cnt[top[i]] * 100 / total));
    }
    memset(g_prof.cnt, 0, (n + 1) * sizeof *g_prof.cnt);   /* a tick in between loses one sample */
    g_prof.samples = 0;
}

#endif /* DC_PROF_H */
