/* dc_prof.h -- the hardware profile on screen (make HUD=prof, Pinboard #495).
 *
 * Every bench of this port so far is Flycast's clock, and a Dreamcast runs
 * a fight at a quarter of it. Flycast charges nothing for a cache miss, a
 * store into video memory or a seek of the drive, so what the console loses
 * its time to has to be measured on the console. Three instruments, read
 * every 2 s with the rest of the stats (main_dc.c), on the HUD's HW, PV,
 * G0/G1 and S0/S1 lines (#518):
 *
 *   - the SH-4's two performance counters, a pair of events a window, the
 *     pairs in turn (dc_prof_pairs): the cycles the pipeline stood still for
 *     a data-cache miss, an instruction-cache miss, a branch, a register, the
 *     FPU (each a share of the window's cycles, 200 MHz), and the operand
 *     cache's read and write misses, the instructions issued, those issued
 *     in pairs, the FPU's (each thousands a second).
 *   - KallistiOS's PVR stats: the last frame's render, registration and
 *     ready-to-ready times, the vblanks seen in the window; and the texture
 *     memory left and the heap in use, in KB.
 *   - a sampler: TMU1 fires DC_PROF_HZ times a second and the interrupt's
 *     context says where the program was. The PC is looked up in a table of
 *     the program's symbols (dc_prof_map.c, generated by tools/dc_profmap.py
 *     from the linked elf: the Makefile links twice) and counted by symbol
 *     and by group. Shown as each group's share and the hottest symbols.
 *
 * KOS keeps PRFC0 as a 5 ns clock by default; taking it leaves its timers
 * on the TMU's 80 ns one. A sample inside a critical section lands where
 * interrupts came back on. The sampler costs about 0.5% at 2 kHz. */
#ifndef DC_PROF_H
#define DC_PROF_H

#include <kos.h>
#include <dc/perfctr.h>
#include <malloc.h>
#include <arch/timer.h>
#include <arch/irq.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef DC_PROF_HZ
#define DC_PROF_HZ 2000
#endif
#define DC_PROF_GROUPS 14
#define DC_PROF_TOP    6

/* dc_prof_map.c (tools/dc_profmap.py): sorted by address */
extern const uint32_t     g_prof_sym_addr[];
extern const uint8_t      g_prof_sym_group[];
extern const char *const  g_prof_sym_name[];
extern const uint32_t     g_prof_sym_n;
extern const char *const  g_prof_group_name[DC_PROF_GROUPS];
extern const uint8_t      g_prof_group_bios;

typedef struct {
    uint32_t *cnt;          /* samples by symbol; [n] below the program (the BIOS) */
    uint32_t  samples;      /* this window's */
    uint64_t  c0, c1;       /* the counters at the window's start */
    unsigned  pair;         /* dc_prof_pairs[pair] is counting */
    size_t    vbl;          /* the PVR's vblank count at the window's start */
    int       on;
} dc_prof_t;

static dc_prof_t g_prof;

/* TMU1's underflow: where was the program? */
static void dc_prof_tick(irq_t code, irq_context_t *ctx, void *data) {
    (void)code; (void)data;
    timer_clear(TMU1);
    uint32_t pc = ctx->pc, n = g_prof_sym_n, idx = n;
    if (pc >= g_prof_sym_addr[0]) {   /* the last symbol at or below pc */
        uint32_t lo = 0, hi = n;
        while (hi - lo > 1) {
            uint32_t mid = (lo + hi) >> 1;
            if (g_prof_sym_addr[mid] <= pc) lo = mid; else hi = mid;
        }
        idx = lo;
    }
    g_prof.cnt[idx]++;
    g_prof.samples++;
}

/* The counters' events, a pair a window, in turn: the name on the HUD and
 * whether it counts cycles (a share) or events (thousands a second). */
static const struct { perf_cntr_event_t ev[2]; const char *name[2]; uint8_t cycles; } dc_prof_pairs[] = {
    { { PMCR_PIPELINE_FREEZE_BY_DCACHE_MISS_MODE, PMCR_PIPELINE_FREEZE_BY_ICACHE_MISS_MODE }, { "dc", "ic" }, 1 },
    { { PMCR_OPERAND_CACHE_READ_MISS_MODE, PMCR_OPERAND_CACHE_WRITE_MISS_MODE }, { "rm", "wm" }, 0 },
    { { PMCR_INSTRUCTION_ISSUED_MODE, PMCR_PARALLEL_INSTRUCTION_ISSUED_MODE }, { "is", "pi" }, 0 },
    { { PMCR_PIPELINE_FREEZE_BY_BRANCH_MODE, PMCR_PIPELINE_FREEZE_BY_CPU_REGISTER_MODE }, { "br", "rg" }, 1 },
    { { PMCR_PIPELINE_FREEZE_BY_FPU_MODE, PMCR_FPU_INSTRUCTION_ISSUED_MODE }, { "fp", "fi" }, 2 },   /* 2: the first cycles, the second events */
};
#define DC_PROF_PAIRS (sizeof dc_prof_pairs / sizeof dc_prof_pairs[0])

static void dc_prof_counters(unsigned pair) {
    g_prof.pair = pair % DC_PROF_PAIRS;
    perf_cntr_start(PRFC0, dc_prof_pairs[g_prof.pair].ev[0], PMCR_COUNT_CPU_CYCLES);
    perf_cntr_start(PRFC1, dc_prof_pairs[g_prof.pair].ev[1], PMCR_COUNT_CPU_CYCLES);
    g_prof.c0 = perf_cntr_count(PRFC0);
    g_prof.c1 = perf_cntr_count(PRFC1);
}

static int dc_prof_init(void) {
    if (!g_prof_sym_n) return -1;   /* the stub map of the first link */
    g_prof.cnt = calloc(g_prof_sym_n + 1, sizeof *g_prof.cnt);
    if (!g_prof.cnt) return -1;
    dc_prof_counters(0);
    pvr_stats_t st;
    pvr_get_stats(&st);
    g_prof.vbl = st.vbl_count;
    irq_set_handler(EXC_TMU1_TUNI1, dc_prof_tick, NULL);
    timer_prime(TMU1, DC_PROF_HZ, 1);
    timer_start(TMU1);
    g_prof.on = 1;
    return 0;
}

/* One counter's window: a share of the cycles (in tenths of a percent) or
 * thousands of events a second, as "dc=12.3%" or "rm=1234K". */
static char *dc_prof_count(char *o, const char *name, uint64_t n, uint64_t us, int cycles) {
    if (cycles) {
        uint64_t t = n * 1000 / (us * 200u);
        return o + sprintf(o, " %s=%u.%u%%", name, (unsigned)(t / 10), (unsigned)(t % 10));
    }
    return o + sprintf(o, " %s=%uK", name, (unsigned)(n * 1000 / us));   /* n / (us / 1e6) / 1000 */
}

/* The window's lines, `us` long, each without its tag (main_dc.c adds it):
 * HW the counters, PV the PVR and memory, G0/G1 the groups' shares, S0/S1
 * the hottest symbols'. Starts the next window, on the next pair of events. */
enum { DC_PROF_HW, DC_PROF_PV, DC_PROF_G0, DC_PROF_G1, DC_PROF_S0, DC_PROF_S1, DC_PROF_LINES };

static void dc_prof_report(uint64_t us, char l[DC_PROF_LINES][80]) {
    pvr_stats_t st;
    pvr_get_stats(&st);
    struct mallinfo mi = mallinfo();
    if (!us) us = 1;
    /* ms to a tenth */
    #define DC_PROF_MS(ns) (unsigned)((ns) / 1000000u), (unsigned)((ns) / 100000u % 10)
    /* (buf_last_time and the vertex buffer's use stay unset: the frame goes to the TA directly) */
    snprintf(l[DC_PROF_PV], 80, "rnd=%u.%u reg=%u.%u fr=%u.%u vbl=%u tm=%u hp=%u",
             DC_PROF_MS(st.rnd_last_time), DC_PROF_MS(st.reg_last_time), DC_PROF_MS(st.frame_last_time),
             (unsigned)(st.vbl_count - g_prof.vbl), (unsigned)(pvr_mem_available() >> 10), (unsigned)(mi.uordblks >> 10));
    #undef DC_PROF_MS
    g_prof.vbl = st.vbl_count;
    if (!g_prof.on) {
        snprintf(l[DC_PROF_HW], 80, "off (no symbol map)");
        for (int i = DC_PROF_G0; i < DC_PROF_LINES; i++) l[i][0] = 0;
        return;
    }
    uint64_t c0 = perf_cntr_count(PRFC0), c1 = perf_cntr_count(PRFC1);
    unsigned p = g_prof.pair;
    char *o = l[DC_PROF_HW];
    o += sprintf(o, "p=%u", p);
    o = dc_prof_count(o, dc_prof_pairs[p].name[0], c0 - g_prof.c0, us, dc_prof_pairs[p].cycles != 0);
    o = dc_prof_count(o, dc_prof_pairs[p].name[1], c1 - g_prof.c1, us, dc_prof_pairs[p].cycles == 1);
    sprintf(o, " smp=%u hz=%u", (unsigned)g_prof.samples, (unsigned)DC_PROF_HZ);
    dc_prof_counters(p + 1);
    uint32_t n = g_prof_sym_n, total = g_prof.samples ? g_prof.samples : 1;
    uint32_t g[DC_PROF_GROUPS] = { 0 };
    uint32_t top[DC_PROF_TOP];
    int ntop = 0;
    for (uint32_t i = 0; i <= n; i++) {
        uint32_t c = g_prof.cnt[i];
        if (!c) continue;
        g[i < n ? g_prof_sym_group[i] : g_prof_group_bios] += c;
        if (i == n) continue;
        /* keep the DC_PROF_TOP largest, in order */
        int k = ntop;
        while (k > 0 && g_prof.cnt[top[k - 1]] < c) k--;
        if (k < DC_PROF_TOP) {
            if (ntop < DC_PROF_TOP) ntop++;
            for (int j = ntop - 1; j > k; j--) top[j] = top[j - 1];
            top[k] = i;
        }
    }
    /* shares in tenths of a percent: a group of 0.4% still shows */
    for (int row = 0; row < 2; row++) {
        o = l[DC_PROF_G0 + row];
        *o = 0;
        for (int i = row * 7; i < row * 7 + 7 && i < DC_PROF_GROUPS; i++) {
            unsigned t = (unsigned)((uint64_t)g[i] * 1000 / total);
            o += sprintf(o, "%s%s=%u.%u", i == row * 7 ? "" : " ", g_prof_group_name[i], t / 10, t % 10);
        }
    }
    for (int row = 0; row < 2; row++) {
        o = l[DC_PROF_S0 + row];
        *o = 0;
        for (int i = row * 3; i < row * 3 + 3 && i < ntop; i++) {
            unsigned t = (unsigned)((uint64_t)g_prof.cnt[top[i]] * 1000 / total);
            o += sprintf(o, "%s%.16s=%u.%u", i == row * 3 ? "" : " ", g_prof_sym_name[top[i]], t / 10, t % 10);
        }
    }
    memset(g_prof.cnt, 0, (n + 1) * sizeof *g_prof.cnt);   /* a tick in between loses one sample */
    g_prof.samples = 0;
}

#endif /* DC_PROF_H */
