#!/usr/bin/env python3
"""dc_profmap.py -- the code map the hardware profile samples against (dc_prof.h,
make HUD=prof, Pinboard #495).

    sh-elf-nm -n -S m2hle2.elf | python3 dc_profmap.py > dc_prof_map.c
    python3 dc_profmap.py --stub > dc_prof_stub.c

Reads nm's sorted, sized symbol list and writes a C unit with every text
symbol's address, its name (the leading underscore and GCC's .constprop/.isra
suffixes off) and the group it belongs to, by the name's prefix: the AOT's
i960 blocks, Gems' C, the profile's hooks, the i960 and the bus, the COP, the
3D decode, the PVR draw, the tile layers, sound, the disc, KallistiOS, libc.
The Makefile links the program twice: once with the stub (no symbols, the
sampler stays off), then with the map made from that link's elf. The map is
data, so the code sits at the same addresses in both (the Makefile checks).
"""
import re
import sys

# (group name on the HUD, the prefixes of the symbols in it); first match wins.
GROUPS = [
    ("aot", ["aot_"]),
    ("gem", ["gfn_", "gems_", "gcop_", "gch_", "gso_", "gsi_", "g4a_", "g70_", "calc_", "os_set",
             "osage_", "rear_", "get_frame", "efc_"]),
    ("hok", ["sfight_", "sfc_", "fvipers_", "m2snake_", "m2_spin", "sky_"]),
    ("960", ["emu_", "i960", "ib_", "jt_", "irqt_", "timers_", "mem_", "bus_", "mslow", "profile_",
             "hle_", "backup_", "log_", "input_", "irq_region"]),
    ("cop", ["sharc_", "cop_", "copro"]),
    ("geo", ["geo3d_", "geo_", "geodl_"]),
    ("drw", ["dp_", "pvr_", "dc_frame", "ls_", "sq_", "dc_video"]),
    ("til", ["tile", "tl_", "tr_", "tmap", "s24_"]),
    ("snd", ["scsp_", "sound_", "m68k", "snd_", "ds_", "adx_", "spu_", "aica", "g2_", "shle_", "sfx_",
             "dc_sound", "dc_hook_sound"]),
    ("dsc", ["pg_", "cdrom_", "syscall_gdrom", "gdc_", "dc_rom", "dc_window", "dc_layout", "g1_"]),
    ("kos", ["thd_", "irq_", "timer_", "genwait", "sem_", "mutex_", "cond_", "cont_", "maple_", "vid_",
             "bfont", "fs_", "dcload", "syscall_", "arch_", "pthread", "rwsem", "kthread", "nmmgr",
             "vmu_", "asic_", "spinlock", "dbgio", "dbglog", "scif_", "mm_", "init_", "hardware_",
             "sysclock", "perf_cntr", "dc_prof", "vblank", "vbl_", "main", "dc_", "iso_", "dma_", "fb_",
             "null_", "mmu_", "ubc_", "kos_", "wdt_", "tp_", "handle", "enable_", "disable_", "clock_",
             "never_", "find_", "bread_", "map_", "unhandled_", "assert_", "handler_"]),
    ("lib", ["mem", "str", "sqrt", "sin", "cos", "malloc", "free", "calloc", "realloc", "printf",
             "sprintf", "snprintf", "qsort", "stdio_", "cleanup_", "global_", "largebin", "aligned_"]),
    ("bio", []),   # pc below the program: the BIOS, where the GD-ROM syscalls run
    ("oth", []),
]
BIOS = next(i for i, (g, _) in enumerate(GROUPS) if g == "bio")
OTHER = next(i for i, (g, _) in enumerate(GROUPS) if g == "oth")
LIB = next(i for i, (g, _) in enumerate(GROUPS) if g == "lib")

SUFFIX = re.compile(r"\.(constprop|isra|part|cold|lto_priv)[.\d]*$|\.\d+$")


def clean(name):
    if name.startswith("_"):
        name = name[1:]
    while True:
        n = SUFFIX.sub("", name)
        if n == name:
            return name
        name = n


def group(name):
    for i, (_, prefixes) in enumerate(GROUPS):
        for p in prefixes:
            if name.startswith(p):
                return i
    # newlib and libgcc: _malloc_r, __udivsi3, fREe, trunc, puts ...
    if name.startswith("_") or "_" not in name:
        return LIB
    return OTHER


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(syms, out):
    names = ", ".join(c_str(g) for g, _ in GROUPS)
    out.write("/* generated by dreamcast/tools/dc_profmap.py: the hardware profile's code map (dc_prof.h) */\n")
    out.write("#include <stdint.h>\n")
    out.write("const char *const g_prof_group_name[%d] = { %s };\n" % (len(GROUPS), names))
    out.write("const uint8_t g_prof_group_bios = %d;\n" % BIOS)
    out.write("const uint32_t g_prof_sym_n = %d;\n" % len(syms))
    if not syms:
        syms = [(0, "", OTHER)]
    out.write("const uint32_t g_prof_sym_addr[%d] = {\n" % len(syms))
    out.write(",\n".join("    0x%08x" % a for a, _, _ in syms) + "\n};\n")
    out.write("const uint8_t g_prof_sym_group[%d] = {\n" % len(syms))
    out.write(",".join("%d" % g for _, _, g in syms) + "\n};\n")
    out.write("const char *const g_prof_sym_name[%d] = {\n" % len(syms))
    out.write(",\n".join("    " + c_str(n) for _, n, _ in syms) + "\n};\n")


def main():
    if "--stub" in sys.argv[1:]:
        emit([], sys.stdout)
        return
    syms = []
    for line in sys.stdin:
        f = line.split()
        # "addr size type name" for sized symbols; labels without a size are left out
        if len(f) != 4 or f[2] not in ("t", "T", "W", "w"):
            continue
        addr = int(f[0], 16)
        name = clean(f[3])
        if not name:
            continue
        if syms and syms[-1][0] == addr:   # aliases: the first name stands
            continue
        syms.append((addr, name, group(name)))
    syms.sort()
    emit(syms, sys.stdout)


if __name__ == "__main__":
    main()
