#!/usr/bin/env python3
"""Bake the lobby's fonts into src/ui/ps3ui_fonts.h.

The PS3 port draws its lobby with two faces of Sega's own (FMH3 font 1, the
Latin of a Japanese gothic, and font 2, a heavy extended grotesque). We do not
ship those. We ship the nearest open fonts (SIL OFL 1.1, from google/fonts),
fixed at one instance and cut down to ASCII, and place them with the PS3's
measured metrics (ps3ui.h does that; this script only makes the bytes):

  title  Anybody, wdth 150 wght 900        font 2: "PLAYER MATCH", counts, VS, READY
  text   M PLUS 1p Medium                  font 1: hints, labels, messages
  mono   M PLUS 1 Code, wght 500           font 1 as the PS3 lays out names (23 px cells)

  python tools/ps3ui/bake_fonts.py --anybody Anybody[wdth,wght].ttf \
      --mplus MPLUS1p-Medium.ttf --mcode MPLUS1Code[wght].ttf

The three files are https://github.com/google/fonts/tree/main/ofl/{anybody,mplus1p,mplus1code}.
Needs fontTools (pip install fonttools).
"""
import argparse, io, os
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CHARS = [c for c in range(0x20, 0x7F)] + [0xA9, 0xAE, 0xD7, 0x2026]
# The page's typography on top of that: no-break space, middle dot, en and em
# dashes, curly quotes, bullet, arrows.
WEB_EXTRA = [0xA0, 0xB7, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022,
             0x2190, 0x2191, 0x2192, 0x2193]
# M PLUS draws the ellipsis centred, the Japanese way; English text on the page
# reads better with the browser's own, so the web cut leaves it out.
WEB_CHARS = [c for c in CHARS if c != 0x2026] + WEB_EXTRA
LICENCES = ['OFL-Anybody.txt', 'OFL-MPLUS.txt', 'OFL-MPLUS1Code.txt']


def bake(path, axes, chars=CHARS, flavor=None):
    f = TTFont(path)
    if axes and 'fvar' in f:
        f = instancer.instantiateVariableFont(f, axes)
    opts = subset.Options()
    opts.layout_features = ['kern']
    opts.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]   # keep copyright + licence
    opts.notdef_outline = True
    opts.hinting = False
    opts.desubroutinize = True
    s = subset.Subsetter(opts)
    s.populate(unicodes=chars)
    s.subset(f)
    if 'glyf' not in f:
        raise SystemExit(f'{path}: CFF outlines; stb_truetype wants TrueType')
    if flavor:
        f.flavor = flavor
    buf = io.BytesIO()
    f.save(buf)
    return buf.getvalue()


def c_array(name, data):
    lines = [f'static const unsigned char {name}[{len(data)}] = {{']
    for i in range(0, len(data), 20):
        lines.append('    ' + ','.join(str(b) for b in data[i:i + 20]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--anybody', required=True)
    ap.add_argument('--mplus', required=True)
    ap.add_argument('--mcode', required=True)
    ap.add_argument('--out', default=os.path.join(ROOT, 'src', 'ui', 'ps3ui_fonts.h'))
    ap.add_argument('--site', help='also write the fonts as WOFF2 (and their licences) into this directory')
    a = ap.parse_args()
    faces = [
        ('title', a.anybody, {'wdth': 150, 'wght': 900}),
        ('text', a.mplus, None),
        ('mono', a.mcode, {'wght': 500}),
    ]
    fonts = [('ps3ui_font_' + key, bake(path, axes)) for key, path, axes in faces]
    if a.site:
        import shutil
        os.makedirs(a.site, exist_ok=True)
        for key, path, axes in faces:
            data = bake(path, axes, WEB_CHARS, 'woff2')
            with open(os.path.join(a.site, key + '.woff2'), 'wb') as fp:
                fp.write(data)
            print(f'{key}.woff2: {len(data)} bytes')
        for name in LICENCES:
            shutil.copyfile(os.path.join(ROOT, 'licenses', name), os.path.join(a.site, name))
    out = ['/* Generated by tools/ps3ui/bake_fonts.py -- do not edit.',
           ' *',
           ' * Anybody (c) The Anybody Project Authors; M PLUS 1p and M PLUS 1 Code',
           ' * (c) The M+ (FONTS) Project Authors. SIL Open Font License 1.1: see',
           ' * licenses/OFL-Anybody.txt, OFL-MPLUS.txt, OFL-MPLUS1Code.txt. Instanced and',
           ' * subset to ASCII; these are Modified Versions under the OFL and keep',
           ' * their original names only as the licence allows (no Reserved Font Name).',
           ' */',
           '#ifndef PS3UI_FONTS_H', '#define PS3UI_FONTS_H', '']
    for name, data in fonts:
        out.append(c_array(name, data))
        out.append('')
    out.append('#endif')
    with open(a.out, 'w', newline='\n') as fp:
        fp.write('\n'.join(out) + '\n')
    for name, data in fonts:
        print(f'{name}: {len(data)} bytes')


if __name__ == '__main__':
    main()
